name: Release Plugin

on:
  push:
    tags: [ '*' ]  # Any tag

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yaml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Rename with tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG="${{ github.ref_name }}"
        mv artifacts/plugin-build/onlyoffice-textcure.plugin "onlyoffice-textcure-${TAG}.plugin"

    - uses: softprops/action-gh-release@v2
      with:
        files: onlyoffice-textcure-${{ github.ref_name }}.plugin
